name: Codecov

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  codecov:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 8
    - uses: eskatos/gradle-command-action@v2
      with:
        arguments: test
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./parser/build/reports/jacoco/report.xml, ./interpreter/build/reports/jacoco/report.xml, ./actorsystem-servicecontract/build/reports/jacoco/report.xml, ./actorsystem-impl/build/reports/jacoco/report.xml
        name: codecov-actorlang
        fail_ci_if_error: true
