name: Quality Gates

on:
  push:
    branches:
      - master
      - develop
      - devops/**
  pull_request:
    branches:
      - master
      - develop

jobs:
  verify:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 8
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: ktlintCheck
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: test

